# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatIsCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  
end

target 'WhatIsCode DEV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  
end
